name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:
  # wheels for python2.7 are not build. However it should still be tested
  test_python27:
    name: Test for Python2.7
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: Install Levenshtein
        run: pip install .

      - name: Test
        run: pytest tests

  build_wheels:
    name: Build wheel on ${{ matrix.os }}/auto/${{matrix.python_tag}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_tag: [ "cp35-*", "cp36-*", "cp37-*", "cp38-*", "cp39-*"]
        os: [windows-latest, macos-latest]
    env:
      CIBW_BUILD: ${{matrix.python_tag}}
      CIBW_TEST_REQUIRES: pytest hypothesis pandas
      CIBW_TEST_COMMAND: pytest {package}/tests
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_apple_silicon:
    name: Build wheel on macos-latest/universal2+arm64/cp39-*
    runs-on: macos-latest
    env:
      CIBW_BUILD: "cp39-*"
      CIBW_ARCHS_MACOS: "universal2 arm64"
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_manylinux:
    name: Build wheels on ubuntu-latest/${{matrix.arch}}/${{matrix.python_tag}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [auto, aarch64, ppc64le, s390x]
        python_tag: [ "cp35-*", "cp36-*", "cp37-*", "cp38-*", "cp39-*"]
    env:
      CIBW_ARCHS_LINUX: ${{matrix.arch}}
      CIBW_BUILD: ${{matrix.python_tag}}
      CIBW_TEST_SKIP: "*-manylinux_{aarch64,ppc64le,s390x}"
      CIBW_TEST_REQUIRES: pytest hypothesis pandas
      CIBW_TEST_COMMAND: pytest {package}/tests
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU

      - name: Build wheel
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_pypy:
    name: Build wheel on ${{ matrix.os }}/auto/${{matrix.python_tag}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_tag: [ "pp36-*", "pp37-*"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CIBW_BUILD: ${{matrix.python_tag}}
      CIBW_TEST_REQUIRES: pytest hypothesis pandas
      CIBW_TEST_COMMAND: pytest {package}/tests
      CIBW_BUILD_VERBOSITY: 3

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: |
          pip3 install build; python3 -m build --sdist
          # test whether tarball contains all files required for compiling
          pip3 install dist/Levenshtein-*.tar.gz
          pip3 uninstall Levenshtein --yes

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  deploy-wheels:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [test_python27, build_wheels, build_wheels_apple_silicon, build_wheels_manylinux, build_wheels_pypy, build_sdist]
    name: deploy wheels to pypi
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
